collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"



url: "https://knows1.github.io/repository/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
